### ISSUE TITLE
Problem with identity server 4

### ISSUE THREAD

**Issue by Eridau** [iayti/CleanArchitecture#35]
Hello, I'm trying to setup identity server 4 for production, and the application keeps erroring out when it runs in production mode, any idea how I can solve this?

**Comment by iayti** [comment]
Hi,
I can't give a clear answer without seeing the error. If you can share the error let me check.

If you're experimenting with changing the environment, it might not be getting the changes in appsetting.Production.json.

Have a nice coding 😊

**Comment by iayti** [comment]
Closed due to lack of response
