### ISSUE TITLE
Secure ASP.NET Core Web API using API Key Authentication

### ISSUE THREAD

**Issue by chuki2** [iayti/CleanArchitecture#37]
Hi, instead of generate token by authenticate using email and password.  Any idea how to implement API Key with in your clean architecture?

**Comment by iayti** [comment]
Hi,

I added the API Key for the JWT token example. If you are using the theme while developing a monolith application, you will need Login/Register. If you are using it for microservice architectures, Login will not be needed. You can use the proper external token directly.

Here's what I plan to add and change in the future
* I plan to remove Identity Server. Change IS4 to [openiddict](https://github.com/openiddict/openiddict-core) or add manually
* Client.WorkerService project to Blazor WebUI

**Comment by chuki2** [comment]
Ok great, solved my issues. I use the redis so I can terminate the token anytime.
